<a href="https://colab.research.google.com/github/23PA1A05E0/ML/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment-1


importing the numpy library

In [ ]:
import numpy as np

Creating two arrays a & b

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b = np.empty_like(a)

1. Perform arithmetic operations on NumPy arrays

In [ ]:
#addition
print(np.add(a,b))
#subraction
print(np.subtract(a,b))
#multiply
print(np.multiply(a,b))
#divide
print(np.divide(a,b))
#sqrt
print(np.sqrt(a*b))


[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 2. 3.]
 [4. 5. 6.]]


2.Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
#mean of a
print(np.mean(a))
#standard deviation of a
print(np.std(a))

3.5
1.707825127659933


3.Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
x = np.array(range(10,50,5))
print(x)
#If you want to include the inside range(10,51,5)

[10 15 20 25 30 35 40 45]


4. Reshape the array into a 2x4 matrix.



In [ ]:
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr)
print("shape")
print(arr.shape)
# reshape
reshaped_arr = arr.reshape(2,4)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
shape
(4, 2)
[[1 2 3 4]
 [5 6 7 8]]


5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):

• Extract the sub-matrix containing the last two rows and first two columns.


• Replace all elements greater than 4 with 0.

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# Extract the sub-matrix containing the last two rows and first two columns.
sub_arr = arr[1:,:2]
print(sub_arr)
# Replace all elements greater than 4 with 0.
# in original array
arr[arr>4] = 0
print(arr)
# in sub matrix
sub_arr[sub_arr>4] = 0
print(sub_arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]
[[4 0]
 [0 0]]


6. Create two 1D arrays:


• a = np.array([1, 2, 3])


• b = np.array([4, 5, 6])


• Perform element-wise addition, multiplication, and division.

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)
#we can built-in methods
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


7. Create a random NumPy array of size (4, 4). Compute:


• Mean of each column.


• Maximum value of the entire array.


• Sum of all elements.

In [ ]:
rm = np.random.randint(23,size=(4,4))
print(rm)
# Mean of each column.
print("mean of each column:",end=" ")
print(np.mean(rm,axis=0))
# Maximum value of the entire array.
print("maximum element:",end=" ")
print(np.max(rm))
#Sum of all elements in arr
print("sum of array:",np.sum(rm))

[[15 16  7  9]
 [ 5 22 18 14]
 [22  7 15 15]
 [ 5  8 22 18]]
mean of each column: [11.75 13.25 15.5  14.  ]
maximum element: 22
sum of array: 218


8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
the result by 2

In [ ]:
arr = np.array([1,2,3,4])
add_arr = arr+10
print(add_arr)
mul_arr = add_arr*2
print(mul_arr)

[11 12 13 14]
[22 24 26 28]


9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:


In [ ]:
arr = np.random.randint(100,size=(3,4,5))
print(arr)

[[[55 26 91 52 36]
  [43 84 34 55 42]
  [79 19 80 47 91]
  [79 18 64 85  5]]

 [[ 6 25 75 23 16]
  [66 58 24 67 92]
  [33 89 20  2 71]
  [26 30 43 94 31]]

 [[35 49 57 25  5]
  [16 19 61 29 34]
  [54 56 13 21 41]
  [69 83 23 36 29]]]


* . Extract the second "layer" (i.e., the second 2D array) in the first dimension

In [ ]:
#By using slicing
print(arr[1])
#By using indexing
print(arr[1,:,:])

[[ 6 25 75 23 16]
 [66 58 24 67 92]
 [33 89 20  2 71]
 [26 30 43 94 31]]
[[ 6 25 75 23 16]
 [66 58 24 67 92]
 [33 89 20  2 71]
 [26 30 43 94 31]]


* . Extract the first two rows and the last three columns from each "layer."

In [ ]:
# using slicing
print(arr[0:2,1:,0:3])

[[[43 84 34]
  [79 19 80]
  [79 18 64]]

 [[66 58 24]
  [33 89 20]
  [26 30 43]]]


*.Replace all elements divisible by 3 with -1.

In [ ]:
arr[arr%3==0] = -1
print(arr)

[[[55 26 91 52 -1]
  [43 -1 34 55 -1]
  [79 19 80 47 91]
  [79 -1 64 85  5]]

 [[-1 25 -1 23 16]
  [-1 58 -1 67 92]
  [-1 89 20  2 71]
  [26 -1 43 94 31]]

 [[35 49 -1 25  5]
  [16 19 61 29 34]
  [-1 56 13 -1 41]
  [-1 83 23 -1 29]]]


10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:

In [ ]:
a = np.random.randint(1,21,size=(3,3))
print(a)

[[ 1  8  1]
 [16  1  9]
 [ 7  2  5]]


 *.Subtract the mean of each row from its respective elements (row-wise
normalization)

In [ ]:
print(a)
for i in range(3):
  a[i] = a[i]-np.mean(a[i])
print(a)

[[ 1  8  1]
 [16  1  9]
 [ 7  2  5]]
[[-2  4 -2]
 [ 7 -7  0]
 [ 2 -2  0]]


• Create a new array by squaring all the elements in arr

In [ ]:
squared_a = a**2
print(squared_a)

[[ 4 16  4]
 [49 49  0]
 [ 4  4  0]]


• Find the indices of the top 3 maximum values in the entire array

In [22]:
a = np.random.randint(1,21,size=(3,3))
print("Original array:")
print(a)

# Flatten the array
flat_a = a.flatten()
print("Flattened array:")
print(flat_a)

top_3_indices = np.argpartition(flat_a, -3)[-3:]

top_3_2d_indices = np.unravel_index(top_3_indices, a.shape)
top_3_values = flat_a[top_3_indices]
print("Top 3 maximum values:")
print(top_3_values)
print("\nIndices of the top 3 maximum values in the array:")
print(top_3_2d_indices)
#or we can simplify
print("\nIndices of the top 3 maximum values in the array:")
row_index,col_index = np.unravel_index(np.argsort(a.flatten())[-3:],a.shape)
for i in range(3):
  print(a[row_index[i] ,col_index[i]], "->index:" ,[row_index[i] ,col_index[i]])




Original array:
[[ 5  8  9]
 [ 7  3  2]
 [18 19  1]]
Flattened array:
[ 5  8  9  7  3  2 18 19  1]
Top 3 maximum values:
[ 9 19 18]

Indices of the top 3 maximum values in the array:
(array([0, 2, 2]), array([2, 1, 0]))

Indices of the top 3 maximum values in the array:
9 ->index: [0, 2]
18 ->index: [2, 0]
19 ->index: [2, 1]
